### ISSUE TITLE
TODO: Dangers of manipulation without violating authentication and how to manage this.

### ISSUE THREAD

**Issue by squarooticus** [squarooticus/draft-krose-multicast-security#10]
I didn't leave myself enough information in this TODO to understand what the actual concern is. Ideas?

**Comment by GrumpyOldTroll** [comment]
I assume this is talking about fields that are not authenticated?  Like maybe IP length with evil UDP options appended?  Or I guess dropping packets?  Not sure what else isn't authenticated, but since this isn't specific to AMBI maybe there's header fields not covered by TESLA in some cases or something?
Also possibly things like discovery?

Nothing else coming to mind.  I don't recall talking about this in particular...
