### ISSUE TITLE
Forward secrecy elaboration

### ISSUE THREAD

**Issue by squarooticus** [squarooticus/draft-krose-multicast-security#6]
Do we need to think more about, and then describe, a model in which forward secrecy is achieved through key management? For instance, obviously a static key protecting the payload which is protected by a rotating key which is itself protected by long-term keys provides no forward secrecy for the content.

**Comment by GrumpyOldTroll** [comment]
I think a rotating ephemeral key that's required to be discarded after rotation is the same as what TLS provides, right?  As long as the earlier keys aren't recoverable after rotation I think you get the same forward secrecy?

But we probably do need to think about it and describe it some.

I was originally thinking extending AMBI to define the parameters for data packet encryption should work, and then maybe adding a key identifier to the manifest.  Since you raised the concern that it shouldn't be possible to start from the (S,G) )and find the key, I've been thinking that the key itself definitely shouldn't be provided from inside the AMBI metadata, but also perhaps not even the uri (and that would be another out of band thing the app would need to know in order to get started).

It's making me think maybe it's not as easy as I was hoping, and I'm not quite sure whether it should be a separate protocol or whether it should be squeezed inside AMBI.  But I think providing a key id in the manifest is useful, which pushes me toward "integrated with AMBI".
